export const USERS = [
  { id: "1", name: "Jay", avatar: "🦁" },
  { id: "2", name: "Gloria", avatar: "🦋" },
  { id: "3", name: "Claire", avatar: "🐘" },
  { id: "4", name: "Phil", avatar: "🐦" },
  { id: "5", name: "Mitchell", avatar: "🐺" },
  { id: "6", name: "Cameron", avatar: "🦉" },
  { id: "7", name: "Haley", avatar: "🐯" },
  { id: "8", name: "Luke", avatar: "🦢" },
  { id: "9", name: "Manny", avatar: "🐻" },
  { id: "10", name: "Lily", avatar: "🦄" },
  { id: "11", name: "Joe", avatar: "🦚" },
  { id: "12", name: "Dylan", avatar: "🐶" },
  { id: "13", name: "George", avatar: "🦑" },
  { id: "14", name: "Isabella", avatar: "🦀" },
  { id: "15", name: "Lucas", avatar: "🐋" },
  { id: "16", name: "Charlotte", avatar: "🐬" },
  { id: "17", name: "Alexander", avatar: "🐡" },
  { id: "18", name: "Katalina", avatar: "🐚" },
  { id: "19", name: "Jerry", avatar: "🐠" },
  { id: "20", name: "Estelle", avatar: "🦞" },
  { id: "21", name: "Petra", avatar: "🐙" },
  { id: "22", name: "Brooke", avatar: "🦐" },
] as const;
