import { User } from "./interfaces";

export const USERS: User[] = [
  { id: "1", name: "Jay", avatar: "🦁", isOnline: false },
  { id: "2", name: "Gloria", avatar: "🦋", isOnline: false },
  { id: "3", name: "Claire", avatar: "🐘", isOnline: false },
  { id: "4", name: "Phil", avatar: "🐦", isOnline: false },
  { id: "5", name: "Mitchell", avatar: "🐺", isOnline: false },
  { id: "6", name: "Cameron", avatar: "🦉", isOnline: false },
  { id: "7", name: "Haley", avatar: "🐯", isOnline: false },
  { id: "8", name: "Luke", avatar: "🦢", isOnline: false },
  { id: "9", name: "Manny", avatar: "🐻", isOnline: false },
  { id: "10", name: "Lily", avatar: "🦄", isOnline: false },
  { id: "11", name: "Joe", avatar: "🦚", isOnline: false },
  { id: "12", name: "Dylan", avatar: "🐶", isOnline: false },
  { id: "13", name: "George", avatar: "🦑", isOnline: false },
  { id: "14", name: "Isabella", avatar: "🦀", isOnline: false },
  { id: "15", name: "Lucas", avatar: "🐋", isOnline: false },
  { id: "16", name: "Charlotte", avatar: "🐬", isOnline: false },
  { id: "17", name: "Alexander", avatar: "🐡", isOnline: false },
  { id: "18", name: "Katalina", avatar: "🐚", isOnline: false },
  { id: "19", name: "Jerry", avatar: "🐠", isOnline: false },
  { id: "20", name: "Estelle", avatar: "🦞", isOnline: false },
  { id: "21", name: "Petra", avatar: "🐙", isOnline: false },
  { id: "22", name: "Brooke", avatar: "🦐", isOnline: false },
];
